PyAuthGG/Administration.py,sha256=5_0UqFKMT1FGbgorb-AE5S3lFggNlwpLaVwwWJU_fNc,4435
PyAuthGG/Application.py,sha256=cVLpeGMDp86vpmBP4L4P-IMSNDJ3SeQDjk7lsXdh1PI,3109
PyAuthGG/Exceptions.py,sha256=gOeQp--DV-ouJyonestakzVj0xSlJyZjaYYFVHbjTF0,114
PyAuthGG/__init__.py,sha256=rG-rHaOURVsEIGxoi9IaNA2tsWzbrBtLazBcgHm4Yl0,487
PyAuthGG-1.0.6.dist-info/LICENSE.md,sha256=YjpQJBWyP9cAUTHzT47TLN48vMQc2ffkYyLa69QK3Uo,1083
PyAuthGG-1.0.6.dist-info/METADATA,sha256=1SmLvg1RWDdudy9KG4SyREBPNiDpskbLfV0j2uSAd-0,3106
PyAuthGG-1.0.6.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
PyAuthGG-1.0.6.dist-info/top_level.txt,sha256=imSBwuebYLd4JifE0PrULv6ACWY7utZspOpTLfM-COM,9
PyAuthGG-1.0.6.dist-info/RECORD,,
